// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: grpc/scheduling.proto

package scheduling

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SchedulingService_CreateRequest_FullMethodName        = "/api.v1.scheduling.SchedulingService/CreateRequest"
	SchedulingService_ListRequests_FullMethodName         = "/api.v1.scheduling.SchedulingService/ListRequests"
	SchedulingService_GetRequest_FullMethodName           = "/api.v1.scheduling.SchedulingService/GetRequest"
	SchedulingService_UpdateRequest_FullMethodName        = "/api.v1.scheduling.SchedulingService/UpdateRequest"
	SchedulingService_DeleteRequest_FullMethodName        = "/api.v1.scheduling.SchedulingService/DeleteRequest"
	SchedulingService_CreateShipment_FullMethodName       = "/api.v1.scheduling.SchedulingService/CreateShipment"
	SchedulingService_UpdateShipmentStatus_FullMethodName = "/api.v1.scheduling.SchedulingService/UpdateShipmentStatus"
	SchedulingService_ListShipments_FullMethodName        = "/api.v1.scheduling.SchedulingService/ListShipments"
	SchedulingService_GetShipment_FullMethodName          = "/api.v1.scheduling.SchedulingService/GetShipment"
)

// SchedulingServiceClient is the client API for SchedulingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingServiceClient interface {
	CreateRequest(ctx context.Context, in *CreateRequestProto, opts ...grpc.CallOption) (*RequestResponse, error)
	ListRequests(ctx context.Context, in *ListRequestsProto, opts ...grpc.CallOption) (*ListRequestsResponse, error)
	GetRequest(ctx context.Context, in *GetRequestProto, opts ...grpc.CallOption) (*RequestResponse, error)
	UpdateRequest(ctx context.Context, in *UpdateRequestProto, opts ...grpc.CallOption) (*RequestResponse, error)
	DeleteRequest(ctx context.Context, in *DeleteRequestProto, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateShipment(ctx context.Context, in *CreateShipmentProto, opts ...grpc.CallOption) (*ShipmentResponse, error)
	UpdateShipmentStatus(ctx context.Context, in *UpdateShipmentProto, opts ...grpc.CallOption) (*ShipmentResponse, error)
	ListShipments(ctx context.Context, in *ListShipmentsProto, opts ...grpc.CallOption) (*ListShipmentsResponse, error)
	GetShipment(ctx context.Context, in *GetShipmentProto, opts ...grpc.CallOption) (*ShipmentResponse, error)
}

type schedulingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingServiceClient(cc grpc.ClientConnInterface) SchedulingServiceClient {
	return &schedulingServiceClient{cc}
}

func (c *schedulingServiceClient) CreateRequest(ctx context.Context, in *CreateRequestProto, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, SchedulingService_CreateRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListRequests(ctx context.Context, in *ListRequestsProto, opts ...grpc.CallOption) (*ListRequestsResponse, error) {
	out := new(ListRequestsResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListRequests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetRequest(ctx context.Context, in *GetRequestProto, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, SchedulingService_GetRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) UpdateRequest(ctx context.Context, in *UpdateRequestProto, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, SchedulingService_UpdateRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) DeleteRequest(ctx context.Context, in *DeleteRequestProto, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SchedulingService_DeleteRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) CreateShipment(ctx context.Context, in *CreateShipmentProto, opts ...grpc.CallOption) (*ShipmentResponse, error) {
	out := new(ShipmentResponse)
	err := c.cc.Invoke(ctx, SchedulingService_CreateShipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) UpdateShipmentStatus(ctx context.Context, in *UpdateShipmentProto, opts ...grpc.CallOption) (*ShipmentResponse, error) {
	out := new(ShipmentResponse)
	err := c.cc.Invoke(ctx, SchedulingService_UpdateShipmentStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListShipments(ctx context.Context, in *ListShipmentsProto, opts ...grpc.CallOption) (*ListShipmentsResponse, error) {
	out := new(ListShipmentsResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListShipments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetShipment(ctx context.Context, in *GetShipmentProto, opts ...grpc.CallOption) (*ShipmentResponse, error) {
	out := new(ShipmentResponse)
	err := c.cc.Invoke(ctx, SchedulingService_GetShipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServiceServer is the server API for SchedulingService service.
// All implementations must embed UnimplementedSchedulingServiceServer
// for forward compatibility
type SchedulingServiceServer interface {
	CreateRequest(context.Context, *CreateRequestProto) (*RequestResponse, error)
	ListRequests(context.Context, *ListRequestsProto) (*ListRequestsResponse, error)
	GetRequest(context.Context, *GetRequestProto) (*RequestResponse, error)
	UpdateRequest(context.Context, *UpdateRequestProto) (*RequestResponse, error)
	DeleteRequest(context.Context, *DeleteRequestProto) (*empty.Empty, error)
	CreateShipment(context.Context, *CreateShipmentProto) (*ShipmentResponse, error)
	UpdateShipmentStatus(context.Context, *UpdateShipmentProto) (*ShipmentResponse, error)
	ListShipments(context.Context, *ListShipmentsProto) (*ListShipmentsResponse, error)
	GetShipment(context.Context, *GetShipmentProto) (*ShipmentResponse, error)
	mustEmbedUnimplementedSchedulingServiceServer()
}

// UnimplementedSchedulingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSchedulingServiceServer struct {
}

func (UnimplementedSchedulingServiceServer) CreateRequest(context.Context, *CreateRequestProto) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequest not implemented")
}
func (UnimplementedSchedulingServiceServer) ListRequests(context.Context, *ListRequestsProto) (*ListRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequests not implemented")
}
func (UnimplementedSchedulingServiceServer) GetRequest(context.Context, *GetRequestProto) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedSchedulingServiceServer) UpdateRequest(context.Context, *UpdateRequestProto) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (UnimplementedSchedulingServiceServer) DeleteRequest(context.Context, *DeleteRequestProto) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRequest not implemented")
}
func (UnimplementedSchedulingServiceServer) CreateShipment(context.Context, *CreateShipmentProto) (*ShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShipment not implemented")
}
func (UnimplementedSchedulingServiceServer) UpdateShipmentStatus(context.Context, *UpdateShipmentProto) (*ShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShipmentStatus not implemented")
}
func (UnimplementedSchedulingServiceServer) ListShipments(context.Context, *ListShipmentsProto) (*ListShipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShipments not implemented")
}
func (UnimplementedSchedulingServiceServer) GetShipment(context.Context, *GetShipmentProto) (*ShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipment not implemented")
}
func (UnimplementedSchedulingServiceServer) mustEmbedUnimplementedSchedulingServiceServer() {}

// UnsafeSchedulingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServiceServer will
// result in compilation errors.
type UnsafeSchedulingServiceServer interface {
	mustEmbedUnimplementedSchedulingServiceServer()
}

func RegisterSchedulingServiceServer(s grpc.ServiceRegistrar, srv SchedulingServiceServer) {
	s.RegisterService(&SchedulingService_ServiceDesc, srv)
}

func _SchedulingService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_CreateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).CreateRequest(ctx, req.(*CreateRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestsProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListRequests(ctx, req.(*ListRequestsProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetRequest(ctx, req.(*GetRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_UpdateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).UpdateRequest(ctx, req.(*UpdateRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_DeleteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).DeleteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_DeleteRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).DeleteRequest(ctx, req.(*DeleteRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_CreateShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShipmentProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).CreateShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_CreateShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).CreateShipment(ctx, req.(*CreateShipmentProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_UpdateShipmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShipmentProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).UpdateShipmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_UpdateShipmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).UpdateShipmentStatus(ctx, req.(*UpdateShipmentProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListShipments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShipmentsProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListShipments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListShipments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListShipments(ctx, req.(*ListShipmentsProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipmentProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_GetShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetShipment(ctx, req.(*GetShipmentProto))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingService_ServiceDesc is the grpc.ServiceDesc for SchedulingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.scheduling.SchedulingService",
	HandlerType: (*SchedulingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequest",
			Handler:    _SchedulingService_CreateRequest_Handler,
		},
		{
			MethodName: "ListRequests",
			Handler:    _SchedulingService_ListRequests_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _SchedulingService_GetRequest_Handler,
		},
		{
			MethodName: "UpdateRequest",
			Handler:    _SchedulingService_UpdateRequest_Handler,
		},
		{
			MethodName: "DeleteRequest",
			Handler:    _SchedulingService_DeleteRequest_Handler,
		},
		{
			MethodName: "CreateShipment",
			Handler:    _SchedulingService_CreateShipment_Handler,
		},
		{
			MethodName: "UpdateShipmentStatus",
			Handler:    _SchedulingService_UpdateShipmentStatus_Handler,
		},
		{
			MethodName: "ListShipments",
			Handler:    _SchedulingService_ListShipments_Handler,
		},
		{
			MethodName: "GetShipment",
			Handler:    _SchedulingService_GetShipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/scheduling.proto",
}
