// Package warehouse provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package warehouse

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Inventory Alerts
	// (GET /api/v1/alerts)
	ListAlerts(c *gin.Context)
	// Set Inventory Threshold
	// (PUT /api/v1/alerts/threshold)
	SetThreshold(c *gin.Context)
	// List Items
	// (GET /api/v1/items)
	ListItems(c *gin.Context, params ListItemsParams)
	// Create Item
	// (POST /api/v1/items)
	CreateItem(c *gin.Context)
	// Delete Item
	// (DELETE /api/v1/items/{itemId})
	DeleteItem(c *gin.Context, itemId int32)
	// Get Item
	// (GET /api/v1/items/{itemId})
	GetItem(c *gin.Context, itemId int32)
	// Update Item
	// (PUT /api/v1/items/{itemId})
	UpdateItem(c *gin.Context, itemId int32)
	// List Warehouses
	// (GET /api/v1/warehouses)
	ListWarehouses(c *gin.Context)
	// Create Warehouse
	// (POST /api/v1/warehouses)
	CreateWarehouse(c *gin.Context)
	// Delete Warehouse
	// (DELETE /api/v1/warehouses/{id})
	DeleteWarehouse(c *gin.Context, id int32)
	// Get Warehouse
	// (GET /api/v1/warehouses/{id})
	GetWarehouse(c *gin.Context, id int32)
	// Update Warehouse
	// (PUT /api/v1/warehouses/{id})
	UpdateWarehouse(c *gin.Context, id int32)
	// Get Inventory
	// (GET /api/v1/warehouses/{id}/inventory)
	GetInventory(c *gin.Context, id int32)
	// Add Inventory
	// (POST /api/v1/warehouses/{id}/inventory/add)
	AddInventory(c *gin.Context, id int32)
	// Remove Inventory
	// (POST /api/v1/warehouses/{id}/inventory/remove)
	RemoveInventory(c *gin.Context, id int32)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAlerts operation middleware
func (siw *ServerInterfaceWrapper) ListAlerts(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAlerts(c)
}

// SetThreshold operation middleware
func (siw *ServerInterfaceWrapper) SetThreshold(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetThreshold(c)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", c.Request.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListItems(c, params)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId int32

	err = runtime.BindStyledParameter("simple", false, "itemId", c.Param("itemId"), &itemId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItem(c, itemId)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId int32

	err = runtime.BindStyledParameter("simple", false, "itemId", c.Param("itemId"), &itemId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, itemId)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId int32

	err = runtime.BindStyledParameter("simple", false, "itemId", c.Param("itemId"), &itemId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateItem(c, itemId)
}

// ListWarehouses operation middleware
func (siw *ServerInterfaceWrapper) ListWarehouses(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListWarehouses(c)
}

// CreateWarehouse operation middleware
func (siw *ServerInterfaceWrapper) CreateWarehouse(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWarehouse(c)
}

// DeleteWarehouse operation middleware
func (siw *ServerInterfaceWrapper) DeleteWarehouse(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteWarehouse(c, id)
}

// GetWarehouse operation middleware
func (siw *ServerInterfaceWrapper) GetWarehouse(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWarehouse(c, id)
}

// UpdateWarehouse operation middleware
func (siw *ServerInterfaceWrapper) UpdateWarehouse(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWarehouse(c, id)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// AddInventory operation middleware
func (siw *ServerInterfaceWrapper) AddInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddInventory(c, id)
}

// RemoveInventory operation middleware
func (siw *ServerInterfaceWrapper) RemoveInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveInventory(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/alerts", wrapper.ListAlerts)
	router.PUT(options.BaseURL+"/api/v1/alerts/threshold", wrapper.SetThreshold)
	router.GET(options.BaseURL+"/api/v1/items", wrapper.ListItems)
	router.POST(options.BaseURL+"/api/v1/items", wrapper.CreateItem)
	router.DELETE(options.BaseURL+"/api/v1/items/:itemId", wrapper.DeleteItem)
	router.GET(options.BaseURL+"/api/v1/items/:itemId", wrapper.GetItem)
	router.PUT(options.BaseURL+"/api/v1/items/:itemId", wrapper.UpdateItem)
	router.GET(options.BaseURL+"/api/v1/warehouses", wrapper.ListWarehouses)
	router.POST(options.BaseURL+"/api/v1/warehouses", wrapper.CreateWarehouse)
	router.DELETE(options.BaseURL+"/api/v1/warehouses/:id", wrapper.DeleteWarehouse)
	router.GET(options.BaseURL+"/api/v1/warehouses/:id", wrapper.GetWarehouse)
	router.PUT(options.BaseURL+"/api/v1/warehouses/:id", wrapper.UpdateWarehouse)
	router.GET(options.BaseURL+"/api/v1/warehouses/:id/inventory", wrapper.GetInventory)
	router.POST(options.BaseURL+"/api/v1/warehouses/:id/inventory/add", wrapper.AddInventory)
	router.POST(options.BaseURL+"/api/v1/warehouses/:id/inventory/remove", wrapper.RemoveInventory)
}
