// Package warehouse provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package warehouse

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Item defines model for Item.
type Item struct {
	Description *string `json:"description,omitempty"`
	Id          *int32  `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Unit        *string `json:"unit,omitempty"`
}

// Warehouse defines model for Warehouse.
type Warehouse struct {
	Id       *int32  `json:"id,omitempty"`
	Location *string `json:"location,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// SetThresholdJSONBody defines parameters for SetThreshold.
type SetThresholdJSONBody struct {
	ItemId    int32 `json:"itemId"`
	Threshold int32 `json:"threshold"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Page  *int32  `form:"page,omitempty" json:"page,omitempty"`
	Size  *int32  `form:"size,omitempty" json:"size,omitempty"`
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// CreateItemJSONBody defines parameters for CreateItem.
type CreateItemJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Unit        string  `json:"unit"`
}

// UpdateItemJSONBody defines parameters for UpdateItem.
type UpdateItemJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Unit        *string `json:"unit,omitempty"`
}

// CreateWarehouseJSONBody defines parameters for CreateWarehouse.
type CreateWarehouseJSONBody struct {
	Location *string `json:"location,omitempty"`
	Name     string  `json:"name"`
}

// UpdateWarehouseJSONBody defines parameters for UpdateWarehouse.
type UpdateWarehouseJSONBody struct {
	Location *string `json:"location,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// AddInventoryJSONBody defines parameters for AddInventory.
type AddInventoryJSONBody struct {
	Amount int32 `json:"amount"`
	ItemId int32 `json:"itemId"`
}

// RemoveInventoryJSONBody defines parameters for RemoveInventory.
type RemoveInventoryJSONBody struct {
	Amount int32 `json:"amount"`
	ItemId int32 `json:"itemId"`
}

// SetThresholdJSONRequestBody defines body for SetThreshold for application/json ContentType.
type SetThresholdJSONRequestBody SetThresholdJSONBody

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody CreateItemJSONBody

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody UpdateItemJSONBody

// CreateWarehouseJSONRequestBody defines body for CreateWarehouse for application/json ContentType.
type CreateWarehouseJSONRequestBody CreateWarehouseJSONBody

// UpdateWarehouseJSONRequestBody defines body for UpdateWarehouse for application/json ContentType.
type UpdateWarehouseJSONRequestBody UpdateWarehouseJSONBody

// AddInventoryJSONRequestBody defines body for AddInventory for application/json ContentType.
type AddInventoryJSONRequestBody AddInventoryJSONBody

// RemoveInventoryJSONRequestBody defines body for RemoveInventory for application/json ContentType.
type RemoveInventoryJSONRequestBody RemoveInventoryJSONBody
