// Package statistics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package statistics

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetInventoryStats request
	GetInventoryStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRequestStats request
	GetRequestStats(ctx context.Context, params *GetRequestStatsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetShipmentStats request
	GetShipmentStats(ctx context.Context, params *GetShipmentStatsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetInventoryStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInventoryStatsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRequestStats(ctx context.Context, params *GetRequestStatsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequestStatsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetShipmentStats(ctx context.Context, params *GetShipmentStatsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetShipmentStatsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetInventoryStatsRequest generates requests for GetInventoryStats
func NewGetInventoryStatsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/stats/inventory")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRequestStatsRequest generates requests for GetRequestStats
func NewGetRequestStatsRequest(server string, params *GetRequestStatsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/stats/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.StartDate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "startDate", runtime.ParamLocationQuery, *params.StartDate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndDate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "endDate", runtime.ParamLocationQuery, *params.EndDate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetShipmentStatsRequest generates requests for GetShipmentStats
func NewGetShipmentStatsRequest(server string, params *GetShipmentStatsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/stats/shipments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Period != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "period", runtime.ParamLocationQuery, *params.Period); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetInventoryStatsWithResponse request
	GetInventoryStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetInventoryStatsResponse, error)

	// GetRequestStatsWithResponse request
	GetRequestStatsWithResponse(ctx context.Context, params *GetRequestStatsParams, reqEditors ...RequestEditorFn) (*GetRequestStatsResponse, error)

	// GetShipmentStatsWithResponse request
	GetShipmentStatsWithResponse(ctx context.Context, params *GetShipmentStatsParams, reqEditors ...RequestEditorFn) (*GetShipmentStatsResponse, error)
}

type GetInventoryStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct {
		ItemId        *int32  `json:"itemId,omitempty"`
		Name          *string `json:"name,omitempty"`
		TotalQuantity *int32  `json:"totalQuantity,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetInventoryStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInventoryStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRequestStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		ByStatus      *map[string]int32 `json:"byStatus,omitempty"`
		EndDate       *string           `json:"endDate,omitempty"`
		StartDate     *string           `json:"startDate,omitempty"`
		TotalRequests *int32            `json:"totalRequests,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetRequestStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRequestStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetShipmentStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *[]struct {
			Count *int32  `json:"count,omitempty"`
			Week  *string `json:"week,omitempty"`
		} `json:"data,omitempty"`
		Period *string `json:"period,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetShipmentStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetShipmentStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetInventoryStatsWithResponse request returning *GetInventoryStatsResponse
func (c *ClientWithResponses) GetInventoryStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetInventoryStatsResponse, error) {
	rsp, err := c.GetInventoryStats(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInventoryStatsResponse(rsp)
}

// GetRequestStatsWithResponse request returning *GetRequestStatsResponse
func (c *ClientWithResponses) GetRequestStatsWithResponse(ctx context.Context, params *GetRequestStatsParams, reqEditors ...RequestEditorFn) (*GetRequestStatsResponse, error) {
	rsp, err := c.GetRequestStats(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRequestStatsResponse(rsp)
}

// GetShipmentStatsWithResponse request returning *GetShipmentStatsResponse
func (c *ClientWithResponses) GetShipmentStatsWithResponse(ctx context.Context, params *GetShipmentStatsParams, reqEditors ...RequestEditorFn) (*GetShipmentStatsResponse, error) {
	rsp, err := c.GetShipmentStats(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetShipmentStatsResponse(rsp)
}

// ParseGetInventoryStatsResponse parses an HTTP response from a GetInventoryStatsWithResponse call
func ParseGetInventoryStatsResponse(rsp *http.Response) (*GetInventoryStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInventoryStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			ItemId        *int32  `json:"itemId,omitempty"`
			Name          *string `json:"name,omitempty"`
			TotalQuantity *int32  `json:"totalQuantity,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRequestStatsResponse parses an HTTP response from a GetRequestStatsWithResponse call
func ParseGetRequestStatsResponse(rsp *http.Response) (*GetRequestStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRequestStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			ByStatus      *map[string]int32 `json:"byStatus,omitempty"`
			EndDate       *string           `json:"endDate,omitempty"`
			StartDate     *string           `json:"startDate,omitempty"`
			TotalRequests *int32            `json:"totalRequests,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetShipmentStatsResponse parses an HTTP response from a GetShipmentStatsWithResponse call
func ParseGetShipmentStatsResponse(rsp *http.Response) (*GetShipmentStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetShipmentStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *[]struct {
				Count *int32  `json:"count,omitempty"`
				Week  *string `json:"week,omitempty"`
			} `json:"data,omitempty"`
			Period *string `json:"period,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
