// Package statistics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package statistics

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GetShipmentStatsParamsPeriod.
const (
	Monthly GetShipmentStatsParamsPeriod = "monthly"
	Weekly  GetShipmentStatsParamsPeriod = "weekly"
)

// GetRequestStatsParams defines parameters for GetRequestStats.
type GetRequestStatsParams struct {
	StartDate *string `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *string `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetShipmentStatsParams defines parameters for GetShipmentStats.
type GetShipmentStatsParams struct {
	Period *GetShipmentStatsParamsPeriod `form:"period,omitempty" json:"period,omitempty"`
}

// GetShipmentStatsParamsPeriod defines parameters for GetShipmentStats.
type GetShipmentStatsParamsPeriod string
