service:
  # 授权认证服务
  auth:
    host: "auth"
    grpc: "9000"
    rest: "8080"
    postgres:
      host: "postgres"
      port: "5432"
      user: "postgres"
      password: "123456"
      database: "auth"
      sslmode: "disable"

  # 用户服务
  user:
    host: "user"
    grpc: "9001"
    rest: "8081"
    postgres:
      host: "postgres"
      port: "5432"
      user: "postgres"
      password: "123456"
      database: "user"
      sslmode: "disable"

  # 仓库服务
  warehouse:
    host: "warehouse"
    grpc: "9002"
    rest: "8082"
    postgres:
      host: "postgres"
      port: "5432"
      user: "postgres"
      password: "123456"
      database: "warehouse"
      sslmode: "disable"

  # 调度服务
  scheduling:
    host: "scheduling"
    grpc: "9003"
    rest: "8083"
    postgres:
      host: "postgres"
      port: "5432"
      user: "postgres"
      password: "123456"
      database: "scheduling"
      sslmode: "disable"

  # 统计服务
  statistics:
    host: "statistics"
    grpc: "9004"
    rest: "8084"

security:
  encryption_key: "emergency-system-aes-key-32chars"

observation:
  jaeger:
    url: "http://jaeger:14268/api/traces"

gaode_maps:
  api_key: "bff42bf37382382b61e29c13b4964ad4"
  base_url: "https://restapi.amap.com"
