services:
  auth:
    build:
      context: ../internal/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ../internal/common/config:/root/ems/backend/internal/common/config

  user:
    build:
      context: ../internal/user
      dockerfile: Dockerfile
    container_name: user
    ports:
      - "8081:8081"
      - "9001:9001"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ../internal/common/config:/root/ems/backend/internal/common/config

  warehouse:
    build:
      context: ../internal/warehouse
      dockerfile: Dockerfile
    container_name: warehouse
    ports:
      - "8082:8082"
      - "9002:9002"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ../internal/common/config:/root/ems/backend/internal/common/config

  scheduling:
    build:
      context: ../internal/scheduling
      dockerfile: Dockerfile
    container_name: scheduling
    ports:
      - "8083:8083"
      - "9003:9003"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ../internal/common/config:/root/ems/backend/internal/common/config

  statistics:
    build:
      context: ../internal/statistics
      dockerfile: Dockerfile
    container_name: statistics
    ports:
      - "8084:8084"
      - "9004:9004"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ../internal/common/config:/root/ems/backend/internal/common/config

  # postgres database
  postgres:

    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ../migration:/docker-entrypoint-initdb.d

  # Grafana
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana
