// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: grpc/statistics.proto

package statistics

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StatisticsService_GetInventoryStats_FullMethodName = "/api.v1.statistics.StatisticsService/GetInventoryStats"
	StatisticsService_GetRequestStats_FullMethodName   = "/api.v1.statistics.StatisticsService/GetRequestStats"
	StatisticsService_GetShipmentStats_FullMethodName  = "/api.v1.statistics.StatisticsService/GetShipmentStats"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetInventoryStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InventoryStatsResponse, error)
	GetRequestStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*RequestStatsResponse, error)
	GetShipmentStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*ShipmentStatsResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetInventoryStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InventoryStatsResponse, error) {
	out := new(InventoryStatsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetInventoryStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetRequestStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*RequestStatsResponse, error) {
	out := new(RequestStatsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetRequestStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetShipmentStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*ShipmentStatsResponse, error) {
	out := new(ShipmentStatsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetShipmentStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility
type StatisticsServiceServer interface {
	GetInventoryStats(context.Context, *empty.Empty) (*InventoryStatsResponse, error)
	GetRequestStats(context.Context, *StatsRequest) (*RequestStatsResponse, error)
	GetShipmentStats(context.Context, *StatsRequest) (*ShipmentStatsResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticsServiceServer struct {
}

func (UnimplementedStatisticsServiceServer) GetInventoryStats(context.Context, *empty.Empty) (*InventoryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventoryStats not implemented")
}
func (UnimplementedStatisticsServiceServer) GetRequestStats(context.Context, *StatsRequest) (*RequestStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestStats not implemented")
}
func (UnimplementedStatisticsServiceServer) GetShipmentStats(context.Context, *StatsRequest) (*ShipmentStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipmentStats not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetInventoryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetInventoryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetInventoryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetInventoryStats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetRequestStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetRequestStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetRequestStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetRequestStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetShipmentStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetShipmentStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetShipmentStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetShipmentStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.statistics.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventoryStats",
			Handler:    _StatisticsService_GetInventoryStats_Handler,
		},
		{
			MethodName: "GetRequestStats",
			Handler:    _StatisticsService_GetRequestStats_Handler,
		},
		{
			MethodName: "GetShipmentStats",
			Handler:    _StatisticsService_GetShipmentStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/statistics.proto",
}
