// Package scheduling provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package scheduling

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Requests
	// (GET /api/v1/requests)
	ListRequests(c *gin.Context, params ListRequestsParams)
	// Create Request
	// (POST /api/v1/requests)
	CreateRequest(c *gin.Context)
	// Delete Request
	// (DELETE /api/v1/requests/{id})
	DeleteRequest(c *gin.Context, id int32)
	// Get Request
	// (GET /api/v1/requests/{id})
	GetRequest(c *gin.Context, id int32)
	// Update Request
	// (PUT /api/v1/requests/{id})
	UpdateRequest(c *gin.Context, id int32)
	// List Shipments
	// (GET /api/v1/shipments)
	ListShipments(c *gin.Context, params ListShipmentsParams)
	// Create Shipment
	// (POST /api/v1/shipments)
	CreateShipment(c *gin.Context)
	// Get Shipment
	// (GET /api/v1/shipments/{shipmentId})
	GetShipment(c *gin.Context, shipmentId int32)
	// Update Shipment Status
	// (PUT /api/v1/shipments/{shipmentId}/status)
	UpdateShipmentStatus(c *gin.Context, shipmentId int32)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListRequests operation middleware
func (siw *ServerInterfaceWrapper) ListRequests(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRequestsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRequests(c, params)
}

// CreateRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateRequest(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRequest(c)
}

// DeleteRequest operation middleware
func (siw *ServerInterfaceWrapper) DeleteRequest(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRequest(c, id)
}

// GetRequest operation middleware
func (siw *ServerInterfaceWrapper) GetRequest(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRequest(c, id)
}

// UpdateRequest operation middleware
func (siw *ServerInterfaceWrapper) UpdateRequest(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateRequest(c, id)
}

// ListShipments operation middleware
func (siw *ServerInterfaceWrapper) ListShipments(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListShipmentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListShipments(c, params)
}

// CreateShipment operation middleware
func (siw *ServerInterfaceWrapper) CreateShipment(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateShipment(c)
}

// GetShipment operation middleware
func (siw *ServerInterfaceWrapper) GetShipment(c *gin.Context) {

	var err error

	// ------------- Path parameter "shipmentId" -------------
	var shipmentId int32

	err = runtime.BindStyledParameter("simple", false, "shipmentId", c.Param("shipmentId"), &shipmentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter shipmentId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetShipment(c, shipmentId)
}

// UpdateShipmentStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateShipmentStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "shipmentId" -------------
	var shipmentId int32

	err = runtime.BindStyledParameter("simple", false, "shipmentId", c.Param("shipmentId"), &shipmentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter shipmentId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateShipmentStatus(c, shipmentId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/requests", wrapper.ListRequests)
	router.POST(options.BaseURL+"/api/v1/requests", wrapper.CreateRequest)
	router.DELETE(options.BaseURL+"/api/v1/requests/:id", wrapper.DeleteRequest)
	router.GET(options.BaseURL+"/api/v1/requests/:id", wrapper.GetRequest)
	router.PUT(options.BaseURL+"/api/v1/requests/:id", wrapper.UpdateRequest)
	router.GET(options.BaseURL+"/api/v1/shipments", wrapper.ListShipments)
	router.POST(options.BaseURL+"/api/v1/shipments", wrapper.CreateShipment)
	router.GET(options.BaseURL+"/api/v1/shipments/:shipmentId", wrapper.GetShipment)
	router.PUT(options.BaseURL+"/api/v1/shipments/:shipmentId/status", wrapper.UpdateShipmentStatus)
}
