// Package scheduling provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package scheduling

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ItemQuantity defines model for ItemQuantity.
type ItemQuantity struct {
	ItemId   *int32 `json:"itemId,omitempty"`
	Quantity *int32 `json:"quantity,omitempty"`
}

// Request defines model for Request.
type Request struct {
	AssignedTo *int32          `json:"assignedTo,omitempty"`
	Id         *int32          `json:"id,omitempty"`
	Items      *[]ItemQuantity `json:"items,omitempty"`
	Location   *string         `json:"location,omitempty"`
	Status     *string         `json:"status,omitempty"`
	Title      *string         `json:"title,omitempty"`
}

// Shipment defines model for Shipment.
type Shipment struct {
	FromWarehouseId *int32  `json:"fromWarehouseId,omitempty"`
	RequestId       *int32  `json:"requestId,omitempty"`
	ShipmentId      *int32  `json:"shipmentId,omitempty"`
	Status          *string `json:"status,omitempty"`
	ToLocation      *string `json:"toLocation,omitempty"`
	Tracking        *[]struct {
		Location  *string `json:"location,omitempty"`
		Status    *string `json:"status,omitempty"`
		Timestamp *string `json:"timestamp,omitempty"`
	} `json:"tracking,omitempty"`
}

// ListRequestsParams defines parameters for ListRequests.
type ListRequestsParams struct {
	Page   *int32  `form:"page,omitempty" json:"page,omitempty"`
	Size   *int32  `form:"size,omitempty" json:"size,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// CreateRequestJSONBody defines parameters for CreateRequest.
type CreateRequestJSONBody struct {
	Items    []ItemQuantity `json:"items"`
	Location string         `json:"location"`
	Title    string         `json:"title"`
}

// UpdateRequestJSONBody defines parameters for UpdateRequest.
type UpdateRequestJSONBody struct {
	AssignedTo *int32  `json:"assignedTo,omitempty"`
	Status     *string `json:"status,omitempty"`
}

// ListShipmentsParams defines parameters for ListShipments.
type ListShipmentsParams struct {
	Page   *int32  `form:"page,omitempty" json:"page,omitempty"`
	Size   *int32  `form:"size,omitempty" json:"size,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// CreateShipmentJSONBody defines parameters for CreateShipment.
type CreateShipmentJSONBody struct {
	FromWarehouseId int32          `json:"fromWarehouseId"`
	Items           []ItemQuantity `json:"items"`
	RequestId       int32          `json:"requestId"`
	ToLocation      string         `json:"toLocation"`
}

// UpdateShipmentStatusJSONBody defines parameters for UpdateShipmentStatus.
type UpdateShipmentStatusJSONBody struct {
	Location  *string `json:"location,omitempty"`
	Status    string  `json:"status"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// CreateRequestJSONRequestBody defines body for CreateRequest for application/json ContentType.
type CreateRequestJSONRequestBody CreateRequestJSONBody

// UpdateRequestJSONRequestBody defines body for UpdateRequest for application/json ContentType.
type UpdateRequestJSONRequestBody UpdateRequestJSONBody

// CreateShipmentJSONRequestBody defines body for CreateShipment for application/json ContentType.
type CreateShipmentJSONRequestBody CreateShipmentJSONBody

// UpdateShipmentStatusJSONRequestBody defines body for UpdateShipmentStatus for application/json ContentType.
type UpdateShipmentStatusJSONRequestBody UpdateShipmentStatusJSONBody
